import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
  title: "Hesam Shop",
  description: "Generated by Amoo Hesam",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <footer>Thanks for visiting Hesam Shop</footer>
      </body>
    </html>
  )
}
