import type { Metadata } from "next"

import "@mantine/core/styles.css"
import "@mantine/carousel/styles.css"
import "@mantine/notifications/styles.css"
import "./globals.css"

import {
  AppShell,
  AppShellMain,
  AppShellFooter,
  AppShellHeader,
  ColorSchemeScript,
  MantineProvider,
  createTheme,
  mantineHtmlProps,
  Group,
  Button,
} from "@mantine/core"
import Link from "next/link"
import { Notifications } from "@mantine/notifications"

export const metadata: Metadata = {
  title: "Hesam Shop",
  description: "Generated by Amoo Hesam",
}

const theme = createTheme({
  fontFamily: "Open Sans, sans-serif",
  primaryColor: "teal",
  autoContrast: true,
  luminanceThreshold: 0.3,
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider defaultColorScheme={"dark"} theme={theme}>
          <Notifications position="bottom-center" />
          <AppShell
            padding="md"
            header={{ height: 50 }}
            footer={{ height: 30 }}
          >
            <AppShellHeader>
              <Group p="xs">
                <Button size="xs" component={Link} variant="filled" href={"/"}>
                  Home
                </Button>
                <Button
                  size="xs"
                  component={Link}
                  variant="filled"
                  href={"/marketplace"}
                >
                  Shop
                </Button>
              </Group>
            </AppShellHeader>

            <AppShellMain>{children}</AppShellMain>
            <AppShellFooter>Thanks for visiting Newsha Shop</AppShellFooter>
          </AppShell>
        </MantineProvider>
      </body>
    </html>
  )
}
